config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'posts#index'

  get 'about' => 'pages#about'

  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
    has_many :comments
    validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    http_basic_authenticate_with name:"imzoughene" , password:"123456", only: [:destroy]
    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(comment_params)
        redirect_to post_path(@post)
    end

    def destroy
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
        @comment.destroy
        redirect_to post_path(@post)
    end

    private def comment_params
        params.require(:comment).permit(:username,:body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about
        @title = "imzoughene"
        @content = "This is the content page"

    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    http_basic_authenticate_with name:"imzoughene" , password:"123456", except: [:index, :show]

    def index
        @posts = Post.all
    end

    def new
        @post = Post.new

    end

    def show
        @post = Post.find(params[:id])
    end

    def create
        #render plain: params[:post].inspect
        @post = Post.new(post_params)

        if(@post.save)
            redirect_to @post
        else
            render 'new'
        end     
    end

    def edit
        @post = Post.find(params[:id])
    end


    def update
        @post = Post.find(params[:id])
        if(@post.update(post_params))
            redirect_to @post
        else
            render 'edit'
        end   
    end


    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to posts_path
    end

    private def post_params
        params.require(:post).permit(:title,:body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comments.html.erb
<div class="row">
    <div class="col-sm-12 py-4">
<% if(@post.comments.length) %>
<h3>Comments</h3>
<% end %>
<ul>
<% @post.comments.each do |elem| %>
    <li>
    <strong> <%= elem.username %></strong> : <%= elem.body %>
    
    <%= link_to "[X]", [elem.post,elem],
    method: :delete, 
    data:{confirm: 'Are you sure ?'} %>
    </li>
<% end %>
</ul>
</div>
</div>

app/views/comments/_form.html.erb
<div class="row">
    <div class="col-sm-12 py-4">
        <h1>Add Comment</h1>
    </div>
</div>
<%= form_for ([@post,@post.comments.build])   do |f| %>
    <% if (@post.errors.any?) %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
        <% end %>
    <% end %>
    <p>
        <%= f.label :username %><br>
        <%= f.text_field(:username, {:class=>'form-control'}) %><br>
    </p>
    <p>
        <%= f.label :body %><br>
        <%= f.text_area(:body,{:class=>'form-control'}) %><br>
    </p>
    <p>
        <%= f.submit({:class=>'btn btn-primary'}) %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css', media: 'all' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">@Imzoughene | RoR CRUD Demo , Simple Blog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home",posts_path %>
      </li>
    </ul>
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to "Create Post",new_post_path %>
      </li>
    </ul>
  </div>
</nav>
    <div class="container py-3">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>about</h1>
<h2><%= @title %></h2>
<p><%= @content %></p>

app/views/posts/edit.html.erb
<div class="row">
    <div class="col-sm-12 py-4">
        <h1>Edit Post</h1>
    </div>
</div>
<%= form_for :post,url: post_path(@post), method: :patch  do |f| %>
    <% if (@post.errors.any?) %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
        <% end %>
    <% end %>
    <p>
        <%= f.label :title %><br>
        <%= f.text_field(:title, {:class=>'form-control'}) %><br>
    </p>
    <p>
        <%= f.label :body %><br>
        <%= f.text_area(:body,{:class=>'form-control'}) %><br>
    </p>
    <p>
        <%= f.submit({:class=>'btn btn-primary'}) %>
    </p>
<% end %>

app/views/posts/index.html.erb
<div class="row">
    <div class="col-sm-12 py-4">
        <h1>Blog posts</h1>
    </div>
</div>
<div class="row">
<% @posts.each do |elem| %>
    <div class="col-sm-4">
        <div class="card" style="width: 18rem;">
            <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcT4RNVSIH2AA2KY-dHFm9T0Q8P9By-uiLai2Q&usqp=CAU" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title"><b>(<%= elem.id %>)</b> <%= elem.title %></h5>
                <p class="card-text"><%= elem.body %></p>
                <div><%= link_to "Read More", post_path(elem), :class => 'btn btn-default' %></div>
            </div>
        </div>
    </div>
<% end %>
</div>

app/views/posts/new.html.erb
<div class="row">
    <div class="col-sm-12 py-4">
        <h1>Add Post</h1>
    </div>
</div>
<%= form_for :post,url: posts_path   do |f| %>
    <% if (@post.errors.any?) %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
        <% end %>
    <% end %>
    <p>
        <%= f.label :title %><br>
        <%= f.text_field(:title, {:class=>'form-control'}) %><br>
    </p>
    <p>
        <%= f.label :body %><br>
        <%= f.text_area(:body,{:class=>'form-control'}) %><br>
    </p>
    <p>
        <%= f.submit({:class=>'btn btn-primary'}) %>
    </p>
<% end %>

app/views/posts/show.html.erb
<div class="row">
    <div class="col-sm-4">
        <div class="card" style="width: 18rem;">
            <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcT4RNVSIH2AA2KY-dHFm9T0Q8P9By-uiLai2Q&usqp=CAU" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title"><b>(<%= @post.id %>)</b> <%= @post.title %></h5>
                <p class="card-text"><%= @post.body %></p>
                <div>
                <%= link_to "Edit", edit_post_path(@post), :class => 'btn btn-primary' %>
                <%= link_to "Delete", post_path(@post),
                method: :delete, 
                data:{confirm: 'Are you sure ?'},
                :class => 'btn btn-danger' %>
                </div>
            </div>
        </div>
    </div>
</div>

<%= render 'comments/comments' %>
<%= render 'comments/form' %>